baseURL = "/"

defaultContentLanguage = "en"
theme = "hugo-bearblog"

enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

[languages]
  [languages.en]
    weight = 1
    # language code
    languageCode = "en"
    # website title
    title = "dan's internet pad"
    # language name
    languageName = "English"
    # default amount of posts in each pages
    pagination.pagerSize = 10
    # date format
    # Menu Info
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 2
      [languages.en.params]
        # site description
        description = "About LoveIt Theme"
        dateFormatToUse = "2006-01-02"
        # site keywords
        keywords = ["Theme", "Hugo"]
        # site default theme ("light", "dark", "auto")
        defaultTheme = "auto"
        # Home Page Info
        [languages.en.params.home]
          # Home Page Profile
          [languages.en.params.home.profile]
            enable = true
            # URL of avatar shown in home page
            avatarURL = "/images/avatar.png"
            # subtitle shown in home page
            subtitle = "Software engineer, fitness enthusiast, Canadian."
            # whether to use typeit animation for subtitle
            typeit = true
            # whether to show social links
            social = true
          # Home Page Posts
          [languages.en.params.home.posts]
            enable = true
            # special amount of posts in each home posts page
            paginate = 5
            # default behavior when you don't set "hiddenFromHomePage" in front matter
            defaultHiddenFromHomePage = false
        # Social Info in home page
        [languages.en.params.social]
          GitHub = "dang3r"
          Linkedin = "dcardoza"
          Twitter = "_dcardoza"

        # Social Share Links in post page
        [languages.en.params.share]
          enable = true
          Twitter = true
          Facebook = true
          Linkedin = true
        
[params]


# Markup related configuration in Hugo
[markup]
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Author Info
[author]
  name = "Daniel Cardoza"
  link = ""

# Sitemap Info
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks Info (https://gohugo.io/content-management/urls/#permalinks)
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":filename"

# Options to make output .md files
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]